## Análise exploratória

### Fundamentos teóricos

É importante entender os tipos das variáveis consideradas, assim como a distribuição probabilística de origem.  
---
title: "CookBook Ferramentas Estatísticas em R"
author: "LAC-FMB"
date: "05/10/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# 1.Análise exploratória de dados
# BANCO DE DADOS: LBW
##   1.1.Fundamentos teóricos

### Dispersão estatística
É forma de caracterizar um conjunto de dados quanto ao seu comportamento aleatório de dispersão de valores. Existem vários modelos de caracterizar o quão disperso um conjunto de dados está, incluindo desvio padrão, coeficiente de variação, coeficiente de dispersão quartil, entre outros.

### Medidas de tendência central
As medidas de tendência central se referem a formas de definir um valor central dentro de uma distribuição probabilística, elas podem ser uma média, mediana ou moda. A média é a forma mais utilizada, ela consiste em um ponto da distribuição probabilística que é igualmente próximo a todos os demais pontos dentro de uma curva probabilística.

### Distribuição probabilística normal
A distribuição probabilística normal, também conhecida como distribuição de gaussiana, é apenas uma das distribuições matemáticas de probabilidade. É caracterizada por ser parametrizada, possuir dados contínuos, concentração dos valores em torno da média, um desvio padrão (que caracteriza a distância média dos dados à média), simetria em torno do valor central e baixa frequência de valores extremos.

### Teorema do limite central
Postulado inicialmente pelo matemático francês Abraham de Moivre, o teorema conclui que uma série de dados que não possui comportamento semelhantes à uma distribuição probabilística normal, quando adicionados mais dados referente ao mesmo evento, sua curva de distribuição probabilística irá tender a assemelhar-se com uma distribuição normal.

### Gramática de dados
Após fase de coleta, é possível que a grande quantidade de dados não permita uma visualização clara dos eventos e desfechos avaliados, até por que muitos podem estar em forma de caracteres numéricos ou valores lógicos TRUE/FALSE ou YES/NO. Para isso, os recursos gráficos facilitam a interpretação dos dados. É muito comum que esses dados sejam representados em gráficos.


##   1.2.Códigos e prática

### 1.2.1.Baixar e Instalar Bibliotecas
  Para esta aula utilizaremos apenas* funções nativas do R, sem necessidade de instalar ou carregar bibliotecas adicionais.
  
  
### 1.2.2.Banco de dados e variaveis
####  1.2.2.1.Ler o banco de dados em excel
``` {BD}
BD <- read_excel("drive:/caminho/do/banco_de/dados.xlsx")
```
#### 1.2.2.2.Visualizar o banco de dados no RStudio
``` {BD}
View(BD)
```
#### 1.2.2.3.Definir os tipos de variáveis
qualitativas: [b] categórica binária, [m] multi categórica
quantitativas: [d] discreta, [c] contínua
``` {BD}  
low_input <- "digite_aqui_o_código_da_variável"
age_input <- "digite_aqui_o_código_da_variável"
lwt_input <- "digite_aqui_o_código_da_variável"
race_input <- "digite_aqui_o_código_da_variável"
smoke_input <- "digite_aqui_o_código_da_variável"
ptl_input <- "digite_aqui_o_código_da_variável"
ht_input <- "digite_aqui_o_código_da_variável"
ui_input <- "digite_aqui_o_código_da_variável"
ftv_input <- "digite_aqui_o_código_da_variável"
bwt_input <- "digite_aqui_o_código_da_variável"
```
  
#### 1.2.2.4.Verificar os tipos de variáveis
01.LOW: qualitativa nominal - cat binária
02.AGE: quantitativa contínua
03.LWT: quantitativa contínua
04.RACE: qualitativa nominal - multi cat
05.SMOKE: qualitativa nominal - cat binária
06.PTL: quantitativa discreta
07.HT: qualitativa nominal - cat binária
08.UI: qualitativa nominal - cat binária
09.FTV: quantitativa discreta
10.BWT: quantitativa contínua")
          
#### 1.2.2.5.Ajustar o BD para as classes das variáveis
``` {BD}      
BD[,c("low","race","smoke","ptl","ht","ui","ftv")] <- lapply(BD[,c("low","race","smoke","ptl","ht","ui","ftv")], as.factor)    
BD$low <- factor(BD$low, levels = c(0,1), labels = c("Não", "Sim"))
BD <- transform(BD, lwt=round(lwt*0.453592,1))
BD$race <- factor(BD$race, levels = c(1,2,3), labels = c("Branca", "Negra","Outra"))
BD$smoke <- factor(BD$smoke, levels = c(0,1), labels = c("Não", "Sim"))
BD$ht <- factor(BD$ht, levels = c(0,1), labels = c("Não", "Sim"))
BD$ui <- factor(BD$ui, levels = c(0,1), labels = c("Não", "Sim"))
```     

#### 1.2.2.5.Verificar as propriedades das variáveis 
(verifica dados como ocorrência, quartis, média, mediana, limites etc):
``` {BD}
summary(BD)
```
(verificar existência de dados faltantes (NA) no banco de dados):
``` {BD}
NAs <- is.na(BD);which(TRUE == NAs)
``` 
    
    
### 1.2.3.Pool de funções
#### 1.2.3.1.Média
##### 1.2.3.1.1.Média simples
      Função: 
``` {BD}
mean(x, na.rm = T/F)
```
x é a variável de entrada
na.rm é utilizado para remover entradas com valores faltando.
    
##### 1.2.3.1.2.Média entre variáveis
Função: 
``` {BD}
tapply(x, index, mean)
```
x é a variável a ser tirada a média.
index é a variável de categorização.
mean é a função de média.

#### 1.2.3.2.Mediana
##### 1.2.3.2.1.Mediana simples
Função: 
``` {BD}
median(x, na.rm = T/F)
```
x é a variável de entrada.
na.rm é utilizado para remover entradas com valores faltando.
    
##### 1.2.3.2.2.Mediana entre variáveis
Função: 
``` {BD}
tapply(x, index, median)
```
x é a variável a ser tirada a mediana.
index é a variável de categorização.
mean é a função de mediana.
    
#### 1.2.3.3.Moda
##### 1.2.3.3.1.Moda simples
No R puro não existe a função moda, então uma opção é criar uma função que avalie os valores, e identifique o de maior ocorrência.
Função:
``` {BD}
y <- BD$age
moda <- function(y, na.rm = T/F) {
  if(na.rm){
    y = y[!is.na(y)] 
    }
  uy <- unique(y)
  tab <- tabulate(match(y, uy))
  uy[tab == max(tab)]
}
moda(y)
```
x é a variável de entrada
na.rm é utilizado para remover entradas com valores faltando.
Outra opção é instalar bibliotecas que contenham ferramentas semeslhantes.A modeest é uma opção. Vamos instalá-la e carregá-la:
``` {BD}
install.packages("modeest", dependencies = T)
library(modeest)
```
Pronto, agora vamos descobrir a moda novamente:
Função: 
``` {BD}
mfv(x)
```
x é a variável de entrada
        
#####    #3.3.2.Moda entre variáveis
Função: 
``` {BD}
tapply(x, index, mfv(x))
```
x é a variável a ser tirada a moda.
index é a variável de categorização.
mean é a função de moda, podendo ser tanto a "moda" quanto a "mfv".
      
  
### 1.2.4.Gráficos
#### 1.2.4.1.Correlação
##### 1.2.4.1.1.Preditores contínuos
Função: 
``` {BD}
scatter.smooth(x,y,main="",xlab="",ylab="")
```
x é o preditor 1, na abscissa
y é o preditor 2, na ordenada
main é o título do gráfico
xlab é o título da abscissa
ylab é o título da ordenada

##### 1.2.4.1.2.Preditores categóricos    
Função: 
``` {BD}
boxplot(y ~ x, data = k, main="Title", xlab="x Title", ylab="y Title")
```
x é o preditor 1, na abscissa
y é o preditor 2, na ordenada
main é o título do gráfico

xlab é o título da abscissa

ylab é o título da ordenada

OBS: é possível identificar no boxplot os limites, outliers, terceiro, segundo (mediana) e primeiro quartis.
  
#### 1.2.4.2.Histogramas
Função:  
``` {BD}
hist(BD$age, main = "Title", xlab = "Title", ylab = "Title", prob = T)
rug(jitter(BD$age));lines( density(x),col="red" )
```
x é a variável de interesse
main é o título do gráfico
xlab é o título da abscissa (Variável)

ylab é o título da ordenada (Frequência)

Breaks são pontos de divisão de cada coluna, na abscissa

rug/jitter mostra a distribuição fina de frequência, na abscissa

### 1.2.5.Exercícios
#### 1.2.5.1.Qual a idade materna média no grupo de fumantes e não fumantes?
``` {BD}
tapply(BD$`Idade materna (anos)`, BD$`Tagabismo durante a gravidez`, mean)
```
#### 1.2.5.2.Plote o gráfico da distribuição das idades maternas analisadas
``` {BD}
hist(BD$`Idade materna (anos)`, main = "Title", xlab = "Title", ylab = "Title", prob = T)
rug(jitter(BD$`Idade materna (anos)`));lines( density(BD$`Idade materna (anos)`),col="red" )
```
#### 1.2.5.3.Qual a mediana do peso materno entre as raças?
``` {BD}
tapply(BD$`Peso materno no último ciclo mestrual (kg)`, BD$Raça, median)
```
#### 1.2.5.4.Qual a moda da idade materna entre os grupos com e sem hipertensão?
``` {BD}
library(modeest)
tapply(BD$`Idade materna (anos)`, BD$`Hipertensão materna`, mfv)
```
#### 1.2.5.5.Plote o gráfico da correlação entre o peso materno e o peso ao nascer
``` {BD}
scatter.smooth(BD$`Peso materno no último ciclo mestrual (kg)`,BD$`Peso ao nascer (g)`,main="",xlab="",ylab="")
```
